In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv(r"D:\MY_ML\multivariablehome.csv")
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      NaN   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [7]:
#df.Bedroom.median()    this will give us an float value i.e 3.5 but we want integer value

import math
bed = math.floor(df.Bedroom.median())
bed

3

In [8]:
df.Bedroom.fillna(bed)         #fill the selected colums NaN values with the median of the column values 

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: Bedroom, dtype: float64

In [9]:
df.Bedroom=df.Bedroom.fillna(bed)  #to fill the NaN value permenantly
df

Area  Bedroom  Age   Price
0  2600      3.0   20  550000
1  3000      4.0   15  565000
2  3200      3.0   18  610000
3  3600      3.0   30  595000
4  4000      5.0    8  760000

In [13]:
#fit is use to train our model with traning set
#here our traning set is a dataframe
#formula : reg.fit(dataframe_name[['All_the_independent_variables']],dataframe_name.dependent_variable)

reg = linear_model.LinearRegression()
reg.fit(df[['Area','Bedroom','Age']],df.Price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
reg.coef_                         #Coefficient i.e m1,m2,m3

array([   137.25, -26025.  ,  -6825.  ])

In [15]:
reg.intercept_                    #Intercept i.e b

383724.9999999998

In [22]:
reg.predict([[3000,3,40]])

array([444400.])

In [23]:
# y=m*x+b
# Price=m1*Area+m2*Bedroom+m3*Age+b
137.25*3000+-26025*3+-6825*40+383724.9999999998

444399.9999999998

In [37]:
#EXERCISE 

import pandas as pd 
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [46]:
df = pd.read_csv(r"D:\MY_ML\HW2_hiring.csv")
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [34]:
df

experience   test_score(out of 10)   interview_score(out of 10)   salary($)
0         NaN                     8.0                            9      50000
1         NaN                     8.0                            6      45000
2        five                     6.0                            7      60000
3         two                    10.0                           10      65000
4       seven                     9.0                            6      70000
5       three                     7.0                           10      62000
6         ten                     NaN                            7      72000
7      eleven                     7.0                            8      80000

In [36]:
df

experience   test_score(out of 10)   interview_score(out of 10)   salary($)
0         NaN                     8.0                            9      50000
1         NaN                     8.0                            6      45000
2        five                     6.0                            7      60000
3         two                    10.0                           10      65000
4       seven                     9.0                            6      70000
5       three                     7.0                           10      62000
6         ten                     NaN                            7      72000
7      eleven                     7.0                            8      80000

In [39]:
a=0
df.experience.fillna(a)


0         0
1         0
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [41]:
a="zero"
df.experience.fillna(a)

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [47]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [48]:
test=df.test_score.mean()
test

7.857142857142857

In [49]:
import math
score=math.floor(test)
score

7

In [51]:
df.test_score.fillna(score)

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     7.0
7     7.0
Name: test_score, dtype: float64

In [52]:
df.test_score=df.test_score.fillna(score)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         7.0                7   72000
7          11         7.0                8   80000

In [56]:
reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
reg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [58]:
reg.intercept_

14992.65144669314

In [59]:
2922.26901502*2+ 2221.30909959*9+ 2147.48256637*6+14992.65144669314

53713.86677126314

In [60]:
reg.predict([[12,10,10]])

array([93747.79628651])