In [1]:
#Predict Diabetes Status

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

data=pd.read_csv(r"D:/Dig/pima.csv")
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [2]:
#if columns has no name

col = ['pregnant','glucose','bp','skin','insulin_level','bmi','pedgiree','age','diabetes_label']
pima = pd.read_csv(r"D:/Dig/pima.csv",names=col)
pima.head()

pregnant  glucose  bp  skin  insulin_level   bmi  pedgiree  age  \
0         6      148  72    35              0  33.6     0.627   50   
1         1       85  66    29              0  26.6     0.351   31   
2         8      183  64     0              0  23.3     0.672   32   
3         1       89  66    23             94  28.1     0.167   21   
4         0      137  40    35            168  43.1     2.288   33   

   diabetes_label  
0               1  
1               0  
2               1  
3               0  
4               1

In [3]:
pima.bp.head()

0    72
1    66
2    64
3    66
4    40
Name: bp, dtype: int64

In [4]:
pima.bmi.head(2)

0    33.6
1    26.6
Name: bmi, dtype: float64

In [5]:
pima.describe()

pregnant     glucose          bp        skin  insulin_level  \
count  768.000000  768.000000  768.000000  768.000000     768.000000   
mean     3.845052  120.894531   69.105469   20.536458      79.799479   
std      3.369578   31.972618   19.355807   15.952218     115.244002   
min      0.000000    0.000000    0.000000    0.000000       0.000000   
25%      1.000000   99.000000   62.000000    0.000000       0.000000   
50%      3.000000  117.000000   72.000000   23.000000      30.500000   
75%      6.000000  140.250000   80.000000   32.000000     127.250000   
max     17.000000  199.000000  122.000000   99.000000     846.000000   

              bmi    pedgiree         age  diabetes_label  
count  768.000000  768.000000  768.000000      768.000000  
mean    31.992578    0.471876   33.240885        0.348958  
std      7.884160    0.331329   11.760232        0.476951  
min      0.000000    0.078000   21.000000        0.000000  
25%     27.300000    0.243750   24.000000        0.000000  
50%     32.000000    0.372500   29.000000        0.000000  
75%     36.600000    0.626250   41.000000        1.000000  
max     67.100000    2.420000   81.000000        1.000000

In [6]:
# My method

X=pima[['pregnant','glucose','bp','skin','insulin_level','bmi','pedgiree','age']]
y=pima['diabetes_label']

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [8]:
print(X_test.shape," ",X_train.shape)

(154, 8)   (614, 8)


In [9]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [10]:
model.fit(X_train,y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
model.score(X_test,y_test)

0.7792207792207793

In [12]:
model.predict([[6,148,72,35,0,33.6,0.627,50]])

array([1], dtype=int64)

In [13]:
model.predict([[0,137,72,45,0,33.6,0.627,20]])

array([0], dtype=int64)

In [14]:
pred=model.predict(X_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.78      0.91      0.84        99
           1       0.77      0.55      0.64        55

    accuracy                           0.78       154
   macro avg       0.78      0.73      0.74       154
weighted avg       0.78      0.78      0.77       154



In [15]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,pred))

0.7792207792207793


In [16]:
y_test.value_counts()

0    99
1    55
Name: diabetes_label, dtype: int64

In [17]:
y_test.mean()

0.35714285714285715

In [18]:
print("Actual diabetes lables : ",y_test.values[0:15])
print("Predicted diabetes lables : ",pred[0:15])

Actual diabetes lables :  [1 1 0 0 0 1 0 0 0 1 1 0 1 0 0]
Predicted diabetes lables :  [0 1 0 0 0 0 0 1 0 1 0 0 0 0 0]


In [19]:
# example of confusion matrix : D:\Dig\confusion_matrix.png
print(metrics.confusion_matrix(y_test,pred))

[[90  9]
 [25 30]]


In [20]:
print(metrics.recall_score(y_test,pred))

0.5454545454545454


In [21]:
pima.isnull().sum()

pregnant          0
glucose           0
bp                0
skin              0
insulin_level     0
bmi               0
pedgiree          0
age               0
diabetes_label    0
dtype: int64